### ISSUE TITLE
systemd service does not exist

### ISSUE THREAD

**Issue by SonaSudebta** [vicinaehq/vicinae#170]
**System information**

- Version: v0.8.0 (5dde11a0)
- Build info: GCC 14.3.1 - Release - LTO
- OS: CachyOS - 
- QT Platform: wayland

**Describe the bug**

I try to start the systemd service using `systemctl enable --user --now vicinae.service` but results with `Failed to enable unit: Unit vicinae.service does not exist`

**To Reproduce**

Install vicinae-bin using yay from AUR:

- `yay -S vicinae-bin`

Run `systemctl enable --user --now vicinae.service`:

- `systemctl enable --user --now vicinae.service`

**Expected behavior**

Service should start and I should be able to set up a keybind to start vicinae using deeplinks

**Screenshots**

<img width="586" height="61" alt="Image" src="https://github.com/user-attachments/assets/fc9d100e-b4e0-4508-8d0f-c82dcb36a06f" />

**Comment by aurelleb** [comment]
@ArjixWasTaken @cilginc  not sure what this is about

**Comment by cilginc** [comment]
I'm pretty sure about `vivinae-bin` works. Can you check systemd service exists:
```bash
ls -la /usr/lib/systemd/user | grep vicinae
```
Also can you execute this and try enabling the service again:
```bash
systemctl daemon-reload
```

**Comment by SonaSudebta** [comment]
This is the result
<img width="665" height="215" alt="Image" src="https://github.com/user-attachments/assets/60d81e6b-0ff6-4e55-afb5-91d08645f850" />

**Comment by SonaSudebta** [comment]
I realize now that I ran it wrong so here's the correct one:
<img width="588" height="64" alt="Image" src="https://github.com/user-attachments/assets/3a84bf7b-a7c7-478a-b1d8-c5849cd88311" />

**Comment by aurelleb** [comment]
so is this fixed @SonaSudebta ?

**Comment by SonaSudebta** [comment]
no it isn't fixed and is still not working

**Comment by cilginc** [comment]
> This is the result
> <img width="665" height="215" alt="Image" src="https://github.com/user-attachments/assets/60d81e6b-0ff6-4e55-afb5-91d08645f850" />

Everything seems normal. Just systemd doesn't want to recognize the service. Try executing these:
```bash
systemctl --user daemon-reexec
systemctl --user daemon-reload
```
I think systemd wants `--user` for reloading user services. 
This should resolve the problem or there is a problem with your systemd.

**Comment by SonaSudebta** [comment]
It still doesn't work

<img width="587" height="148" alt="Image" src="https://github.com/user-attachments/assets/080276cd-5660-4ad0-8d90-4fd10ac8b206" />

.
> This should resolve the problem or there is a problem with your systemd.

I'm not sure why there would be an issue with my systemd as I've never done anything out of the ordinary. if you'd be so kind as to help out, what should I do to see if it is a systemd issue?

**Comment by ArjixWasTaken** [comment]
@SonaSudebta do you have a file at the path `~/.config/systemd/user/vicinae.service`?

**Comment by SonaSudebta** [comment]
That path seems to be a file instead and yes there is a file there, however it's 0 bytes as seen in this image:

<img width="1112" height="672" alt="Image" src="https://github.com/user-attachments/assets/347ef2c0-1305-4db6-8f6d-d6f9b20a8246" />

This is a symlink that I made following instructions provided by GuabeDarteM as per #49. This actually worked until a recent update.
When I try to open the target file for the symlink, it says `The file or folder /usr/lib/systemd/system/vicinae.service does not exist.`

**Comment by ArjixWasTaken** [comment]
that means you used to use `vicinae-git` and had my badly placed systemd unit 😓 (which was fixed after a few days)

simply disable the service and re-enable it

```
systemctl --user disable --now vicinae
systemctl --user enable --now vicinae
```

**Comment by SonaSudebta** [comment]
Alright it works now!! Thanks a lot for the obvious yet not so obvious solution (dunnow why I didn't think of that earlier)
