### ISSUE TITLE
Externally Mounted Drives not showing up in file search, despite manually being added to the inclusion list

### ISSUE THREAD

**Issue by officialnochill** [vicinaehq/vicinae#208]
**System information**

- Version: v0.8.2 (cfd4bd71)
- Build info: GCC 14.3.1 - Release - LTO
- OS: CachyOS - 
- QT Platform: wayland

**Describe the bug**

Externally Mounted Drives not showing up in file search, despite manually being added to the inclusion list

**To Reproduce**

Add externally mounted drive to the inclusion list

**Expected behavior**

External Drive to be indexed and results to show up in the search

**Screenshots**

<img width="230" height="94" alt="Image" src="https://github.com/user-attachments/assets/b859199d-1a1f-400d-a2d6-087102da44a7" />

**Comment by aurelleb** [comment]
did you wait a bit or tried to restart vicinae to see if some of the files come up? Maybe not the very deeply nested files but the top level ones?

**Comment by officialnochill** [comment]
Yes I can confirm that nothing shows up at all

**Comment by aurelleb** [comment]
> Yes I can confirm that nothing shows up at all

can you give us more context about what kind of drive it is and what filesystem it uses

**Comment by officialnochill** [comment]
<img width="2351" height="506" alt="Image" src="https://github.com/user-attachments/assets/ffc65507-0399-488b-964d-10134feb63d2" />

(this is one of them, its an internally connected SATA SSD)

**Comment by aurelleb** [comment]
interesting, we will look into this thank you for the report and the details

**Comment by aurelleb** [comment]
can you try with the newest version? (v0.9.5)

**Comment by officialnochill** [comment]
I've been out of the city, tried now on v0.9.5 but no luck, I have a video on the root drive that should show up after a file rebuild, but no luck

**Comment by aurelleb** [comment]
you should try on latest version, we fixed a lot of things recently regarding file indexing.

**Comment by officialnochill** [comment]
I have got to be unlucky, because still no dice. 

Maybe its related to this? 
https://github.com/vicinaehq/vicinae/issues/341

As mine also doesn't start up on boot, so I have a command on auto run to start up the server on my hyprland setup. 

Maybe its interfering with its indexing

**Comment by officialnochill** [comment]
I just tried symlinking external drive folders to my home drive, and they still don't appear 

<img width="545" height="744" alt="Image" src="https://github.com/user-attachments/assets/9165a5b4-43a1-4b36-bf54-b43734ee8035" />

I also noticed that rebuilding the file index twice in a row can cause the entire program to lock up, unable to be closed.

**Comment by aurelleb** [comment]
for the locking up thing we recently merged something that should fix it.
@quadratech188 do you have any clue why it's not picking that one up?

**Comment by quadratech188** [comment]
Also no idea.
@officialnochill Could you share the server's command-line output for us?

**Comment by officialnochill** [comment]
```
Oct 06 17:48:20 nochill-pc vicinae[36212]: [17:48:20.996] INFO   -  Creating inotify watchers in /home/nochill/Music/Music 
Oct 06 17:48:20 nochill-pc vicinae[36212]: [17:48:20.996] WARN   -  FileSystemWalker needs to be passed a readable directory as its root entrypoint No such file or directory 
Oct 06 17:48:33 nochill-pc vicinae[36212]: [17:48:33.508] INFO   -  Done walking file tree at /home/nochill. Processed 88976 directories and 609724 files in 12 seconds. 
Oct 06 17:48:51 nochill-pc vicinae[36212]: [17:48:51.294] WARN   -  virtual void QtWaylandClient::QWaylandTextInputv3::disableSurface(wl_surface*) Try to disable surface 0x558f3e30a580 with focusing surface 0x558f3dd12f70 

```
Thats with me setting it as a watcher directory, if I set it as one of the regular include paths: 
```

Oct 06 17:51:42 nochill-pc vicinae[1249]: [17:51:42.722] WARN   -  FileSystemWalker needs to be passed a readable directory as its root entrypoint No such file or directory 
Oct 06 17:51:54 nochill-pc vicinae[1249]: [17:51:54.933] INFO   -  Done walking file tree at /home/nochill. Processed 88976 directories and 609731 files in 12 seconds. 

```

**Comment by quadratech188** [comment]
> Oct 06 17:48:20 nochill-pc vicinae[36212]: [17:48:20.996] WARN   -  FileSystemWalker needs to be passed a readable directory as its root entrypoint No such file or directory 

Well, *that* isn't supposed to happen. It's just a simple `std::filesystem::is_directory` call, why is it erroring out?

**Comment by quadratech188** [comment]
Probably not related, but could you share why your mount point is a random UUID?

**Comment by officialnochill** [comment]
> Probably not related, but could you share why your mount point is a random UUID?

<img width="2358" height="1398" alt="Image" src="https://github.com/user-attachments/assets/f37d560c-4528-4d7d-80aa-0b714a7e7a85" />

For all of my non-boot SSD's, I just edited the mount options to mount on boot using gnome-disks and never changed the mount point names 

Probably unrelated, but my external drives are not encrypted, whereas the main boot drive is
