### ISSUE TITLE
Clipboard manager doesn't show copied entries

### ISSUE THREAD

**Issue by WarpFire69** [vicinaehq/vicinae#485]
**System information**

- Version: v0.14.5 (7461b91e)
- Build info: GCC 14.3.1 - Release - LTO
- Provenance: binary_release
- OS: Fedora Linux 42 (Workstation Edition) - 42
- QT Platform: wayland

**Describe the bug**

Every time I try to copy anything. Then I can't use the clipboard manager, because it seems what 

***Trobleshooting***

In the logs of the vicinae server, then the following errors are happening:
Failed to create scan history QSqlError("1299", "Unable to fetch row", "NOT NULL constraint failed: scan_history.created_at")

Failed to insert selection QSqlError("1299", "Unable to fetch row", "NOT NULL constraint failed: selection.created_at")

scan_history. happens at the start when starting the vicinae server.

I have tried to disable disk encryption and that doesn't help. I've tried to clear history and that doesn't work either.

selection happens everytime I try to copy anything.

Output when starting the vicinae server:
`
[09:29:20.962] INFO   -  Activated clipboard server "wlr-clipboard"
[09:29:21.103] INFO   -  Started extension manager /tmp/command.xptEdd
[09:29:21.108] INFO   -  Starting clipboard server "wlr-clipboard"
[09:29:21.108] INFO   -  Killed existing wlr-clip instance
[09:29:21.109] INFO   -  Clipboard server "wlr-clipboard" started successfully.
[09:29:21.110] INFO   -  Started "Qalculate!" calculator backend
[09:29:21.125] INFO   -  This is our first startup, enqueuing a full scan...
[09:29:21.127] WARN   -  Failed to create scan history QSqlError("1299", "Unable to fetch row", "NOT NULL constraint failed: scan_history.created_at")
[09:29:21.127] WARN   -  Not scanning "/home/dzjw" because scan record creation failed with error "Failed to create scan history"
[09:29:21.424] INFO   -  Vicinae server successfully started. Call "vicinae toggle" to toggle the window
[09:29:21.463] ERROR  -  Failed to insert selection QSqlError("1299", "Unable to fetch row", "NOT NULL constraint failed: selection.created_at")
[09:29:21.463] WARN   -  failed to insert selection
[09:29:25.466] INFO   -  Done walking file tree at /home/dzjw. Processed 42505 directories and 407883 files in 4 seconds.
[09:29:28.809] ERROR  -  Failed to insert selection QSqlError("1299", "Unable to fetch row", "NOT NULL constraint failed: selection.created_at")
[09:29:28.809] WARN   -  failed to insert selection
[09:29:41.425] ERROR  -  Failed to insert selection QSqlError("1299", "Unable to fetch row", "NOT NULL constraint failed: selection.created_at")
[09:29:41.425] WARN   -  failed to insert selection
[09:30:49.201] ERROR  -  Failed to insert selection QSqlError("1299", "Unable to fetch row", "NOT NULL constraint failed: selection.created_at")
[09:30:49.201] WARN   -  failed to insert selection
[09:31:11.947] ERROR  -  Failed to insert selection QSqlError("1299", "Unable to fetch row", "NOT NULL constraint failed: selection.created_at")
[09:31:11.947] WARN   -  failed to insert selection
`

The vicinae-wlr-clip application seems to be working fine, because I can see what I copy in the vicinae-wlr-clip app:
`
********** BEGIN PRIMARY SELECTION**********
text/plain;charset=utf-8      Clipboard manager
UTF8_STRING                   Clipboard manager
COMPOUND_TEXT
TEXT                          Clipboard manager
text/plain                    Clipboard manager
STRING                        Clipboard manager
text/plain;charset=utf-8      Clipboard manager
text/plain                    Clipboard manager
********** END PRIMARY SELECTION**********
`

I have tried version 0.14.5, 0.14.4, and 0.14.3 and I'm getting the same issue.

It has worked for me without any issues for a few days, but then all of a sudden it stops working.

**To Reproduce**

Start the vicinae server using:
`vicinae server`

**Expected behavior**

Everytime I try to copy anything. Then it will be visible in the clipboard manager.

**Comment by aurelleb** [comment]
what version were you using when it was still working? Also did you do anything special before that started happening? System update, vicinae update...

These error messages are very weird, one potential reason I could see is a change in sqlite on your system. Or the QT sqlite driver.

Can you try this please:

```
$> sqlite
select unixepoch();
```

**Comment by WarpFire69** [comment]
Funny thing is, that when I roll back to the working version which was 0.14.3 then it still doesn't work.

`
sqlite3
SQLite version 3.47.2 2024-12-07 20:39:59
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> select unixepoch();
1760418329
`

I only updated Vicinae when I started to get issuse to hopefully fix the bug in a newer release.

But I don have a cronjob set up to make DNF upgrade at every boot, perhaps that broke something.

But do you think it's a Vicinae issue?

**Comment by aurelleb** [comment]
it's most likely not a vicinae issue, but I can be wrong of course. The fact that the previous version doesn't work seem to indicate something else on your system broke. But maybe someone else is going to chime in and report the same issue.

**Comment by pravinkori** [comment]
I'm also facing similar issue related to Clipboard History. 

- Version v0.14.5 (commit 7461b91e)
- Build: GCC 14.3.1 - Release - LTO
- Provenance: binary_release
- OS: Arch Linux
- QT Platform: wayland

<img width="792" height="500" alt="Image" src="https://github.com/user-attachments/assets/3f48ed8b-4b4d-4057-afbd-8a773075b4e1" />

**Comment by aurelleb** [comment]
what environment, gnome, kde or something else? what do the logs say? I doubt this is the same issue.

**Comment by pravinkori** [comment]
Sorry for not providing required details. 
Environment is GNOME 49.0 and I read the docs. I think I will have to use Vicinae Gnome Extension

**Comment by aurelleb** [comment]
yeah you need the extension for clipboard, what you see is normal if you are not using it.

**Comment by suhaibkn** [comment]
I was facing a similar issue (Ubuntu 24.04, GNOME 46, Wayland) a few weeks ago.

I had the GNOME extension (1.3.0) installed. After updating Vicinae (to the then latest version) the clipboard history stopped showing newly copied entries (old entries were still visible in the clipboard history).

After messing around for a few hours, I realized that the GNOME extension had also received an update. I updated the extension and clipboard feature started working after that.

TLDR:
Make sure the GNOME extension is not only installed, but that you have the correct version of the extension installed.

**Comment by idlip** [comment]
I face this issue somehow.

I use nixos flake so there is no issue with package.
I use niriWM with gnome xdg portal

- When i open firefox private window (action 2) when I copy with mouse drag I cannot see the copied text in clipboard. But when I paste elsewhere it paste that text only.

below I'm attaching an sample video:

https://github.com/user-attachments/assets/ecc343f9-92c1-4fbb-83b1-62d8b804913d

^ As you see text is not getting shown in clipboard (but can be pasted), but when I copied URL bar link via `Ctrl-c` it shows up in clipboard (magic ?)

or is it application not configured properly by system/package ?

**Comment by idlip** [comment]
^ My above issue was addressed in discord server.

For anyone who face similar issue to mine, I think librewolf private window has some rule over how text is copied.
Since it sends in different `wl-paste -p` output

```
# from regular librewolf window
$  wl-paste -l
COMPOUND_TEXT
SAVE_TARGETS
text/plain;charset=utf-8
UTF8_STRING
TEXT
text/_moz_htmlcontext
text/plain
text/x-moz-url-priv
STRING
text/html
text/_moz_htmlinfo

# from private window
$  wl-paste -l
text/plain
UTF8_STRING
x-kde-passwordManagerHint
SAVE_TARGETS
text/html
text/plain;charset=utf-8
STRING
text/_moz_htmlinfo
TEXT
text/x-moz-url-priv
COMPOUND_TEXT
text/_moz_htmlcontext
```

**Comment by aurelleb** [comment]
Is anyone still having issues with the clipboard? Most of the problems cited in this thread have different origins. Only the first one is very weird.

**Comment by bigdiff** [comment]
> Is anyone still having issues with the clipboard? Most of the problems cited in this thread have different origins. Only the first one is very weird.

I'm having the same problem while copying from all (big number of apps qt apps, terminal, browsers chromium/firefox ...etc)

Using plasma v6.5.0 and vicinae v0.15.4

In the logs I see

```
ERROR  -  wlr-clipboard process exited with status code QProcess::CrashExit
```

**Comment by bigdiff** [comment]
might be related to https://github.com/vicinaehq/vicinae/pull/508

update:
reverting back to v0.14.1 (which was before the mentioned PR merge) does not seem to have resolved the issue.

I still get an error when vicinae tries to start vicinae-wlr-cli

**Comment by aurelleb** [comment]
did you try the latest version?

**Comment by bigdiff** [comment]
> did you try the latest version?

with v0.15.7 I'm getting `16557 segmentation fault (core dumped)  vicinae server`

<details>
<summary>vicinae server</summary>

```
INFO   -  GnomeWindowManager: Detected environment: "KDE/Wayland"
INFO   -  GnomeWindowManager: Not in GNOME environment, skipping
INFO   -  Activated clipboard server "wlr-clipboard"
INFO   -  Started extension manager /run/user/1000/vicinae/extension-manager.js with /run/user/1000/fnm_multishells/4989_1761789713655/bin/node
INFO   -  Starting clipboard server "wlr-clipboard"
INFO   -  Clipboard server "wlr-clipboard" started successfully.
INFO   -  Started "Qalculate!" calculator backend
WARN   -  Ignoring icon theme directory with no index.theme at /usr/share/icons/locolor/index.theme
WARN   -  setSelected called on id "enfocado_dark.json" does not match any valid list item
WARN   -  selectValue: no item with ID: "enfocado_dark.json"
WARN   -  setSelected called on id "enfocado_dark.json" does not match any valid list item
WARN   -  selectValue: no item with ID: "enfocado_dark.json"
WARN   -  setSelected called on id "enfocado_dark.json" does not match any valid list item
WARN   -  selectValue: no item with ID: "enfocado_dark.json"
terminate called after throwing an instance of 'std::runtime_error'
  what():  zwlr data control is not available
ERROR  -  wlr-clipboard process exited with status code QProcess::CrashExit
INFO   -  Vicinae server successfully started. Call "vicinae toggle" to toggle the window
[1]    16557 segmentation fault (core dumped)  vicinae server

```

</details>

**Comment by aurelleb** [comment]
Most likely this #576 @bigdiff

**Comment by bigdiff** [comment]
more logs

<details>
<summary>more logs</summary>

```
Process 86030 (exe) of user 1000 dumped core.

Stack trace of thread 86030:
#0  0x00007f4fa149894c n/a (libc.so.6 + 0x9894c)
#1  0x00007f4fa143e410 raise (libc.so.6 + 0x3e410)
#2  0x00007f4fa142557a abort (libc.so.6 + 0x2557a)
#3  0x00007f4fa1897bf6 _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x97bf6)
#4  0x00007f4fa18b1eba _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xb1eba)
#5  0x00007f4fa18975d9 _ZSt9terminatev (libstdc++.so.6 + 0x975d9)
#6  0x00007f4fa18b2176 __cxa_throw (libstdc++.so.6 + 0xb2176)
#7  0x000055d42ecd3e3b _ZN14CommandLineApp3runEiPPc.cold (/usr/bin/vicinae + 0x97fe3b)
#8  0x000055d42ecb1090 main (/usr/bin/vicinae + 0x95d090)
#9  0x00007f4fa1427675 n/a (libc.so.6 + 0x27675)
#10 0x00007f4fa1427729 __libc_start_main (libc.so.6 + 0x27729)
#11 0x000055d42e97e1a5 _start (/usr/bin/vicinae + 0x62a1a5)
ELF object binary architecture: AMD x86-64

terminate called after throwing an instance of 'std::runtime_error'
  what():  zwlr data control is not available
ERROR  -  wlr-clipboard process exited with status code QProcess::CrashExit

```

</details>

**Comment by WarpFire69** [comment]
I originally created this post.

I can happily report that in version 0.16.1 the clipboard is working for me again.

So somewhere between 0.14.5 - 0.16.1 the clipboard started to work again. I "upgraded" directly from 0.14.5 to 0.16.1. So I can't say which version that actually fixed my issue.

**Comment by bigdiff** [comment]
I can confirm it is fixed, feel free to close
