### ISSUE TITLE
Starting some applications does nothing when vicinae is installed from cachix

### ISSUE THREAD

**Issue by Leka1B** [vicinaehq/vicinae#533]
**System information**

- Version: v0.15.3 (8a1da6df0)
- Build info: GCC 14.3.0 - Release
- Provenance: nix
- OS: NixOS 25.11 (Xantusia) - 25.11
- QT Platform: wayland
- DE: Hyprland/Wayland

**Describe the bug**

Opening some applications results in no visible reaction whatsoever.

Currently the only affected apps that I found were Telegram desktop and AmneziaVPN. Both of them launch fine in cli with the exact same command found in their .desktop files. 
This is a new development though, as they were both launching fine several days ago.

This honestly might be an issue with my system, but i don't even have an idea of how i would diagnose this, as the apps run perfectly otherwise.

**To Reproduce**

- Select Telegram desktop or AmneziaVPN in vicinae
- Press "return"
- Nothing happens
- Check vicinae server's console
- No lines showing i even tried to open these applications

**Expected behavior**

These applications should open, and if something is preventing this it'd be nice to know about it.

**Comment by aurelleb** [comment]
Generally this is an environment problem, are you running vicinae with systemd? If so, do you use something like uwsm to make sure it gets started after Hyprland?

**Comment by Leka1B** [comment]
The systemd integratin in nix is currently not working, as mentioned in #494, so i am starting the vicinae server via hyprland exec-once. 
These applications started perfectly fine, but this changed after I updated the system as a whole, including vicinae itself, and tinkered with other configurations. Unfortunately my configuration is not version controlled as of now, so these changes are hard to replicate and find, if they are what caused this issue.

**Comment by aurelleb** [comment]
Nothing changed with the way applications are launched so that's unlikely, but maybe there is something I'm missing here.

**Comment by Leka1B** [comment]
So it's most likely broken on my end.
If this isn't too much to ask, could you tell me how to view more verbose logs if these are available? Running the server in console does not show much

**Comment by aurelleb** [comment]
I don't think you will be able to get more logs rn cause I'm simply not logging much. There are additional debug logs in some places but that's only if you compile from source in debug mode yourself. I can easily add more logs for app launching related stuff, tho.

**Comment by Diti** [comment]
Same problem on my end. The Vicinae server daemon is active and running, started by [uswm](https://github.com/Vladimir-csp/uwsm), but it seems Vicinae refuses to run applications which need XDG portals to be run (as far as I understand).

My old launcher was able to run `Telegram | xargs hyprctl dispatch exec --` just fine. But Vicinae doesn’t provide a way to pass the selected application to `hyprctl`, so there’s nothing I can do.

My current workaround consists of using `vicinae dmenu`; calling Vicinae like this makes you lose 95 % of the app’s features.

```shell
vicinae app list --json | jaq --raw-output '.[] | select(.hidden == false) | .program' | vicinae dmenu | xargs hyprctl dispatch execr --
```

I’d rather be provided an option to let the user decide which launcher command to use to run XDG applications (something which lets me write `hyprctl dispatch exec %s --` or something like that), so I can let Hyprland do the launching.

**Comment by aurelleb** [comment]
@Diti adding the ability to specify a custom launcher is in the cards but this needs to be fixed regardless, this is definitely not expected behavior.
Do these apps launch properly if you run the vicinae server directly from your hyprland session, instead of invoking it with uwsm?

**Comment by Leka1B** [comment]
I just found my problem. Both these programs were recently updated to Qt 6.10, and stopped launching after this update. Trying to run them from vicinae's environment confirmed it, both applications display this error:
version `Qt_6.10' not found (required by Telegram)

This may be the case due to the cachix binary being built on a system with nixpkgs 25.05 instead of unstable, but any guess is as good as mine. I'll try to rebuild it myself and see if the issue remains.

**Comment by Leka1B** [comment]
As for @Diti's case, I don't understand it at all. Vicinae was able to start telegram perfectly fine before their update, so portals don't seem to be a problem.

Mind you, I'm not well-versed in the ways uwsm works. Do you need to do it this way to launch telegram's background process through systemd?

**Comment by nixfieduser** [comment]
@Leka1B I can confirm that installing the pkg without using the binary cache gets ridden of the issue of not opening certain applications. 

I force the compiling by adding    **inputs.nixpkgs.follows = "nixpkgs";**

I do not know why but removing the substituters from nix settings wasn't enough to force the build, but at least now everything seems fully functional.

**Comment by Leka1B** [comment]
Thanks for confirming it. I've been building the package along with all it's dependencies via nix build for the pask hour to check, but now you saved me the trouble. Didn't know setting follows would work.

This seems to be a large issue with using cachix binaries, as the enviromnent seems to be hard wired at build time (if i understand that correctly). 

Something should definitely be done, as environments might differ, and rebuilding it every time takes a while

**Comment by Diti** [comment]
Wow, @nixfieduser is right! Apps get launched correctly when Vicinae has been properly compiled instead of downloaded from Cachix.

I’ve tried to spend a hour debugging, but I couldn’t manage to find an error message anywhere (to help with this issue)… Very frustrating!

**Comment by Leka1B** [comment]
I think it would be nice if launch errors could be displayed in vicinae server to help with further debugging, perhaps with a --verbose flag

**Comment by aurelleb** [comment]
@Leka1B  right now we report an error only if starting the process fails (missing executable is the most typical cause for this) but we indeed do not monitor whether the process then exits with a non-zero status code. This would require some additional process management logic because right now we just start it detached and call it a day, not worrying about it after that.

This is definitely something that can be done so I will look into it, as this is not the first case of this happening.

**Comment by Leka1B** [comment]
> I do not know why but removing the substituters from nix settings wasn't enough to force the build

That might be due to you already having the version on your system, so no rebuilds are needed.

Most likely the issue is caused by a stale flake.lock file that has an older nixpkgs commit, and using nixpkgs.follows requires vicinae to use a version that differs, hence the cachix binary can't be used and everything gets built from scratch.

This repo's flake.lock shows nixpkgs was modified sep 28, before it got the newer qt-6 version, so i suggest another version bump, and perhaps an automated workflow for updating the lockfile for each cachix build.

**Comment by schromp** [comment]
https://github.com/NixOS/nixpkgs/pull/451675


Vicinae got merged into upstream nix.
As soon as it gets into unstable someone may try to test.

Maybe we should then recommend installing from there because you would get the innate nixos cachix.
Because the main problem with nix in this project currently seems to be the cachix instance

**Comment by Leka1B** [comment]
Shouldn't be a problem anymore, but please comment if you still experience this

**Comment by Diti** [comment]
> Shouldn't be a problem anymore, but please comment if you still experience this

I tried enabling Cachix again after seeing this comment, and my Vicinae no longer works again for some applications, exactly like before. It also doesn’t seem to suggest my most used applications any more.

(And I originally didn’t manage to find a way to revert to the non-Cachix version, even after performing a `nix-collect-garbage` after ensuring Vicinae isn’t present in my configuration; but I rediscovered that the fix is to re-add `inputs.nixpkgs.follows = "nixpkgs"` to the Vicinae input in your flake.)

But I see logs now! Output of `journalctl --boot --unit=vicinae --user` follows. Could it be a `uwsm` problem instead of a Vicinae one?

```
Dec 04 10:22:09 dtphoudespcu systemd[2083]: Started Vicinae server daemon.
Dec 04 10:22:09 dtphoudespcu vicinae[2534]: [10:22:09.915] INFO   -  Initializing vicinae server... 
Dec 04 10:22:09 dtphoudespcu vicinae[2534]: [10:22:09.981] INFO   -  Activated clipboard server "wlr-clipboard" 
Dec 04 10:22:10 dtphoudespcu vicinae[2534]: [10:22:10.075] INFO   -  Started extension manager /run/user/1000/vicinae/extension-manager.js with /nix/store/nvf9kaarb9kqqdbygl9cbzhli1y8yjik-nodejs-22.20.0/bin/node 
Dec 04 10:22:10 dtphoudespcu vicinae[2534]: [10:22:10.078] INFO   -  Starting clipboard server "wlr-clipboard" 
Dec 04 10:22:10 dtphoudespcu vicinae[2534]: [10:22:10.079] INFO   -  Clipboard server "wlr-clipboard" started successfully. 
Dec 04 10:22:10 dtphoudespcu vicinae[2534]: [10:22:10.079] INFO   -  Starting incremental scan for entrypoint /home/diti 
Dec 04 10:22:10 dtphoudespcu vicinae[2534]: [10:22:10.199] INFO   -  Started "Qalculate!" calculator backend 
Dec 04 10:22:10 dtphoudespcu vicinae[2534]: [10:22:10.199] INFO   -  Refreshing Qalculate exchange rates... 
Dec 04 10:22:10 dtphoudespcu vicinae[2534]: [10:22:10.214] WARN   -  Ignoring icon theme directory with no index.theme at /home/diti/.local/share/icons/hicolor/index.theme 
Dec 04 10:22:10 dtphoudespcu vicinae[2534]: [10:22:10.214] WARN   -  Ignoring icon theme directory with no index.theme at /nix/store/08yy8grnd544nh60byjkpc41ng0gjpj9-vicinae/share/icons/hicolor/index.theme 
Dec 04 10:22:10 dtphoudespcu vicinae[2534]: [10:22:10.215] WARN   -  Ignoring icon theme directory with no index.theme at /nix/store/apw386d39c4imw0ijw18s8k9m1f5nkdx-cups-2.4.14/share/icons/hicolor/index.theme 
Dec 04 10:22:10 dtphoudespcu vicinae[2534]: [10:22:10.215] WARN   -  Ignoring icon theme directory with no index.theme at /etc/profiles/per-user/diti/share/icons/hicolor/index.theme 
Dec 04 10:22:10 dtphoudespcu vicinae[2534]: [10:22:10.230] INFO   -  Vicinae server successfully started. Call "vicinae toggle" to toggle the window 
Dec 04 10:22:10 dtphoudespcu vicinae[2534]: [10:22:10.865] INFO   -  Done refreshing exchange rates 
Dec 04 10:22:12 dtphoudespcu vicinae[2534]: [10:22:12.001] INFO   -  Done walking file tree at /home/diti. Processed 25446 directories and 187172 files in 1 seconds. 
Dec 04 10:22:24 dtphoudespcu vicinae[2534]: [10:22:24.150] INFO   -  App started with command line "Telegram --" 
Dec 04 10:22:25 dtphoudespcu systemd-coredump[2974]: Process 2953 (.Telegram-wrapp) of user 1000 dumped core.
                                                     
                                                     Module /nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped without build-id.
                                                     Module libmng.so.2 without build-id.
                                                     Module libjasper.so.7 without build-id.
                                                     Module libLerc.so.4 without build-id.
                                                     Module libtiff.so.6 without build-id.
                                                     Module libwebpdemux.so.2 without build-id.
                                                     Module libraw.so.23 without build-id.
                                                     Module liblcms2.so.2 without build-id.
                                                     Module libbrotlienc.so.1 without build-id.
                                                     Module libjxl_cms.so.0.11 without build-id.
                                                     Module libjxl_threads.so.0.11 without build-id.
                                                     Module libjxl.so.0.11 without build-id.
                                                     Module libyuv.so without build-id.
                                                     Module libavif.so.16 without build-id.
                                                     Module libdeflate.so.0 without build-id.
                                                     Module libImath-3_2.so.30 without build-id.
                                                     Module libOpenEXRCore-3_3.so.32 without build-id.
                                                     Module libIex-3_3.so.32 without build-id.
                                                     Module libIlmThread-3_3.so.32 without build-id.
                                                     Module libOpenEXR-3_3.so.32 without build-id.
                                                     Module libde265.so without build-id.
                                                     Module libheif.so.1 without build-id.
                                                     Module libpipewire-module-session-manager.so without build-id.
                                                     Module libpipewire-module-metadata.so without build-id.
                                                     Module libpipewire-module-adapter.so without build-id.
                                                     Module libpipewire-module-client-device.so without build-id.
                                                     Module libpipewire-module-client-node.so without build-id.
                                                     Module libpipewire-module-protocol-native.so without build-id.
                                                     Module libpipewire-module-rt.so without build-id.
                                                     Module libspa-dbus.so without build-id.
                                                     Module libspa-journal.so without build-id.
                                                     Module libspa-support.so without build-id.
                                                     Module libpsl.so.5 without build-id.
                                                     Module libssh2.so.1 without build-id.
                                                     Module libnghttp2.so.14 without build-id.
                                                     Module libngtcp2.so.16 without build-id.
                                                     Module libngtcp2_crypto_ossl.so.0 without build-id.
                                                     Module libnghttp3.so.9 without build-id.
                                                     Module libFLAC.so.14 without build-id.
                                                     Module libduktape.so.207 without build-id.
                                                     Module libsndfile.so.1 without build-id.
                                                     Module libpxbackend-1.0.so without build-id.
                                                     Module libbrotlicommon.so.1 without build-id.
                                                     Module libkeyutils.so.1 without build-id.
                                                     Module libkrb5support.so.0 without build-id.
                                                     Module libcom_err.so.3 without build-id.
                                                     Module libk5crypto.so.3 without build-id.
                                                     Module libkrb5.so.3 without build-id.
                                                     Module libGLdispatch.so.0 without build-id.
                                                     Module libcap.so.2 without build-id.
                                                     Module libcjson.so.1 without build-id.
                                                     Module libmbedcrypto.so.16 without build-id.
                                                     Module libnettle.so.8 without build-id.
                                                     Module libhogweed.so.6 without build-id.
                                                     Module libtasn1.so.6 without build-id.
                                                     Module libunistring.so.5 without build-id.
                                                     Module libidn2.so.0 without build-id.
                                                     Module libp11-kit.so.0 without build-id.
                                                     Module libvorbisfile.so.3 without build-id.
                                                     Module libmpg123.so.0 without build-id.
                                                     Module libnuma.so.1 without build-id.
                                                     Module libogg.so.0 without build-id.
                                                     Module libvmaf.so.3 without build-id.
                                                     Module libsharpyuv.so.0 without build-id.
                                                     Module libexpat.so.1 without build-id.
                                                     Module libgomp.so.1 without build-id.
                                                     Module libgraphite2.so.3 without build-id.
                                                     Module libpulsecommon-17.0.so without build-id.
                                                     Module libpcre2-8.so.0 without build-id.
                                                     Module libffi.so.8 without build-id.
                                                     Module libselinux.so.1 without build-id.
                                                     Module libpcre2-16.so.0 without build-id.
                                                     Module libb2.so.1 without build-id.
                                                     Module libdouble-conversion.so.3 without build-id.
                                                     Module libicudata.so.76 without build-id.
                                                     Module libicuuc.so.76 without build-id.
                                                     Module libicui18n.so.76 without build-id.
                                                     Module libproxy.so.1 without build-id.
                                                     Module libzstd.so.1 without build-id.
                                                     Module libbrotlidec.so.1 without build-id.
                                                     Module libgssapi_krb5.so.2 without build-id.
                                                     Module libmd4c.so.0 without build-id.
                                                     Module libpng16.so.16 without build-id.
                                                     Module libEGL.so.1 without build-id.
                                                     Module libOpenGL.so.0 without build-id.
                                                     Module libGLX.so.0 without build-id.
                                                     Module libXdmcp.so.6 without build-id.
                                                     Module libXau.so.6 without build-id.
                                                     Module libXi.so.6 without build-id.
                                                     Module libXrender.so.1 without build-id.
                                                     Module libsoxr.so.0 without build-id.
                                                     Module libdrm.so.2 without build-id.
                                                     Module libvdpau.so.1 without build-id.
                                                     Module libva-drm.so.2 without build-id.
                                                     Module libssh.so.4 without build-id.
                                                     Module libsrt.so.1.5 without build-id.
                                                     Module librist.so.4 without build-id.
                                                     Module libgnutls.so.30 without build-id.
                                                     Module libgmp.so.10 without build-id.
                                                     Module libbluray.so.2 without build-id.
                                                     Module libopenmpt.so.0 without build-id.
                                                     Module libbz2.so.1 without build-id.
                                                     Module libxml2.so.16 without build-id.
                                                     Module libxvidcore.so.4 without build-id.
                                                     Module libx265.so.215 without build-id.
                                                     Module libx264.so.164 without build-id.
                                                     Module libwebp.so.7 without build-id.
                                                     Module libvorbisenc.so.2 without build-id.
                                                     Module libvorbis.so.0 without build-id.
                                                     Module libtheoradec.so.2 without build-id.
                                                     Module libtheoraenc.so.2 without build-id.
                                                     Module libSvtAv1Enc.so.3 without build-id.
                                                     Module libspeex.so.1 without build-id.
                                                     Module libopenjp2.so.7 without build-id.
                                                     Module libmp3lame.so.0 without build-id.
                                                     Module libaom.so.3 without build-id.
                                                     Module libzvbi.so.0 without build-id.
                                                     Module libdav1d.so.7 without build-id.
                                                     Module liblzma.so.5 without build-id.
                                                     Module libwebpmux.so.3 without build-id.
                                                     Module libvulkan.so without build-id.
                                                     Module libfreetype.so.6 without build-id.
                                                     Module libfontconfig.so.1 without build-id.
                                                     Module libOpenCL.so.1 without build-id.
                                                     Module libzimg.so.2 without build-id.
                                                     Module libvidstab.so.1.2 without build-id.
                                                     Module libva.so.2 without build-id.
                                                     Module libass.so.9 without build-id.
                                                     Module libfribidi.so.0 without build-id.
                                                     Module libharfbuzz.so.0 without build-id.
                                                     Module libpostproc.so.57 without build-id.
                                                     Module libncursesw.so.6 without build-id.
                                                     Module libabsl_log_severity.so.2508.0.0 without build-id.
                                                     Module libabsl_raw_logging_internal.so.2508.0.0 without build-id.
                                                     Module libabsl_spinlock_wait.so.2508.0.0 without build-id.
                                                     Module libabsl_base.so.2508.0.0 without build-id.
                                                     Module libabsl_string_view.so.2508.0.0 without build-id.
                                                     Module libabsl_strings_internal.so.2508.0.0 without build-id.
                                                     Module libabsl_int128.so.2508.0.0 without build-id.
                                                     Module libabsl_str_format_internal.so.2508.0.0 without build-id.
                                                     Module libabsl_utf8_for_code_point.so.2508.0.0 without build-id.
                                                     Module libabsl_decode_rust_punycode.so.2508.0.0 without build-id.
                                                     Module libabsl_demangle_rust.so.2508.0.0 without build-id.
                                                     Module libabsl_demangle_internal.so.2508.0.0 without build-id.
                                                     Module libabsl_malloc_internal.so.2508.0.0 without build-id.
                                                     Module libabsl_debugging_internal.so.2508.0.0 without build-id.
                                                     Module libabsl_symbolize.so.2508.0.0 without build-id.
                                                     Module libabsl_strerror.so.2508.0.0 without build-id.
                                                     Module libabsl_leak_check.so.2508.0.0 without build-id.
                                                     Module libabsl_stacktrace.so.2508.0.0 without build-id.
                                                     Module libabsl_crc_cpu_detect.so.2508.0.0 without build-id.
                                                     Module libabsl_crc_internal.so.2508.0.0 without build-id.
                                                     Module libabsl_crc32c.so.2508.0.0 without build-id.
                                                     Module libabsl_crc_cord_state.so.2508.0.0 without build-id.
                                                     Module libabsl_tracing_internal.so.2508.0.0 without build-id.
                                                     Module libabsl_time_zone.so.2508.0.0 without build-id.
                                                     Module libabsl_civil_time.so.2508.0.0 without build-id.
                                                     Module libabsl_time.so.2508.0.0 without build-id.
                                                     Module libabsl_kernel_timeout_internal.so.2508.0.0 without build-id.
                                                     Module libabsl_graphcycles_internal.so.2508.0.0 without build-id.
                                                     Module libabsl_synchronization.so.2508.0.0 without build-id.
                                                     Module libabsl_cordz_handle.so.2508.0.0 without build-id.
                                                     Module libabsl_exponential_biased.so.2508.0.0 without build-id.
                                                     Module libabsl_cordz_functions.so.2508.0.0 without build-id.
                                                     Module libabsl_city.so.2508.0.0 without build-id.
                                                     Module libabsl_hash.so.2508.0.0 without build-id.
                                                     Module libabsl_cord_internal.so.2508.0.0 without build-id.
                                                     Module libabsl_cordz_info.so.2508.0.0 without build-id.
                                                     Module libabsl_cord.so.2508.0.0 without build-id.
                                                     Module libabsl_status.so.2508.0.0 without build-id.
                                                     Module libabsl_random_seed_gen_exception.so.2508.0.0 without build-id.
                                                     Module libabsl_random_internal_seed_material.so.2508.0.0 without build-id.
                                                     Module libabsl_random_internal_platform.so.2508.0.0 without build-id.
                                                     Module libabsl_random_internal_randen_slow.so.2508.0.0 without build-id.
                                                     Module libabsl_random_internal_randen_hwaes_impl.so.2508.0.0 without build-id.
                                                     Module libabsl_random_internal_randen_hwaes.so.2508.0.0 without build-id.
                                                     Module libabsl_random_internal_randen.so.2508.0.0 without build-id.
                                                     Module libabsl_random_internal_entropy_pool.so.2508.0.0 without build-id.
                                                     Module libabsl_random_seed_sequences.so.2508.0.0 without build-id.
                                                     Module libabsl_random_distributions.so.2508.0.0 without build-id.
                                                     Module libabsl_hashtablez_sampler.so.2508.0.0 without build-id.
                                                     Module libabsl_raw_hash_set.so.2508.0.0 without build-id.
                                                     Module libabsl_log_internal_globals.so.2508.0.0 without build-id.
                                                     Module libabsl_log_internal_fnmatch.so.2508.0.0 without build-id.
                                                     Module libabsl_vlog_config_internal.so.2508.0.0 without build-id.
                                                     Module libabsl_log_globals.so.2508.0.0 without build-id.
                                                     Module libabsl_flags_commandlineflag_internal.so.2508.0.0 without build-id.
                                                     Module libabsl_flags_commandlineflag.so.2508.0.0 without build-id.
                                                     Module libabsl_flags_private_handle_accessor.so.2508.0.0 without build-id.
                                                     Module libabsl_flags_program_name.so.2508.0.0 without build-id.
                                                     Module libabsl_flags_config.so.2508.0.0 without build-id.
                                                     Module libabsl_flags_reflection.so.2508.0.0 without build-id.
                                                     Module libabsl_flags_marshalling.so.2508.0.0 without build-id.
                                                     Module libabsl_flags_internal.so.2508.0.0 without build-id.
                                                     Module libabsl_log_internal_proto.so.2508.0.0 without build-id.
                                                     Module libabsl_log_entry.so.2508.0.0 without build-id.
                                                     Module libabsl_log_sink.so.2508.0.0 without build-id.
                                                     Module libabsl_log_internal_log_sink_set.so.2508.0.0 without build-id.
                                                     Module libabsl_log_internal_structured_proto.so.2508.0.0 without build-id.
                                                     Module libabsl_log_internal_format.so.2508.0.0 without build-id.
                                                     Module libabsl_examine_stack.so.2508.0.0 without build-id.
                                                     Module libabsl_log_internal_nullguard.so.2508.0.0 without build-id.
                                                     Module libabsl_log_internal_message.so.2508.0.0 without build-id.
                                                     Module libabsl_log_internal_conditions.so.2508.0.0 without build-id.
                                                     Module libabsl_log_internal_check_op.so.2508.0.0 without build-id.
                                                     Module libutf8_validity.so.32.1.0 without build-id.
                                                     Module libabsl_statusor.so.2508.0.0 without build-id.
                                                     Module libabsl_log_initialize.so.2508.0.0 without build-id.
                                                     Module libabsl_die_if_null.so.2508.0.0 without build-id.
                                                     Module libatomic.so.1 without build-id.
                                                     Module libpulse.so.0 without build-id.
                                                     Module libasound.so.2 without build-id.
                                                     Module libgcc_s.so.1 without build-id.
                                                     Module libstdc++.so.6 without build-id.
                                                     Module libxcb-screensaver.so.0 without build-id.
                                                     Module libxcb-record.so.0 without build-id.
                                                     Module libxcb.so.1 without build-id.
                                                     Module libxcb-keysyms.so.1 without build-id.
                                                     Module libxxhash.so.0 without build-id.
                                                     Module libxkbcommon.so.0 without build-id.
                                                     Module libz.so.1 without build-id.
                                                     Module liblz4.so.1 without build-id.
                                                     Module libXtst.so.6 without build-id.
                                                     Module libX11.so.6 without build-id.
                                                     Module libXrandr.so.2 without build-id.
                                                     Module libXfixes.so.3 without build-id.
                                                     Module libXext.so.6 without build-id.
                                                     Module libXdamage.so.1 without build-id.
                                                     Module libXcomposite.so.1 without build-id.
                                                     Module libabsl_throw_delegate.so.2508.0.0 without build-id.
                                                     Module libjpeg.so.62 without build-id.
                                                     Module libcrc32c.so.1 without build-id.
                                                     Module libvpx.so.11 without build-id.
                                                     Module libopenh264.so.7 without build-id.
                                                     Module libopus.so.0 without build-id.
                                                     Module libswscale.so.7 without build-id.
                                                     Module libswresample.so.4 without build-id.
                                                     Module libavutil.so.58 without build-id.
                                                     Module libavformat.so.60 without build-id.
                                                     Module libavcodec.so.60 without build-id.
                                                     Module libpipewire-0.3.so.0 without build-id.
                                                     Module libavfilter.so.9 without build-id.
                                                     Module libhunspell-1.7.so.0 without build-id.
                                                     Module libabsl_strings.so.2508.0.0 without build-id.
                                                     Module libprotobuf-lite.so.32.1.0 without build-id.
                                                     Module libopenal.so.1 without build-id.
                                                     Module librnnoise.so.0 without build-id.
                                                     Module libminizip.so.1 without build-id.
                                                     Stack trace of thread 2953:
                                                     #0  0x0000000000000000 n/a (n/a + 0x0)
                                                     #1  0x00007f74b7ec2974 _ZN25QWaylandCompositorPrivate4initEv (libQt6WaylandCompositor.so.6 + 0xc2974)
                                                     #2  0x000055bb591e2fe7 _ZN7Webview10CompositorC2ERK10QByteArray (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x56d5fe7)
                                                     #3  0x000055bb591be4b1 _ZN7Webview9WebKitGTK12_GLOBAL__N_18Instance12startProcessEv (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x56b14b1)
                                                     #4  0x000055bb591c1dcc _ZN7Webview9WebKitGTK12_GLOBAL__N_18InstanceC2Eb (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x56b4dcc)
                                                     #5  0x000055bb591c4972 _ZN7Webview9WebKitGTK12AvailabilityEv (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x56b7972)
                                                     #6  0x000055bb591b1c4e _ZN7Webview12AvailabilityEv (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x56a4c4e)
                                                     #7  0x000055bb54c8c47c _ZN2Iv10ShowButtonEv (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x117f47c)
                                                     #8  0x000055bb56a2b6fd _ZN4Core11Application3runEv (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x2f1e6fd)
                                                     #9  0x000055bb56aced5a _ZN4Core7Sandbox14notifyOrInvokeEP7QObjectP6QEvent (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x2fc1d5a)
                                                     #10 0x000055bb56acee9e _ZN4Core7Sandbox6notifyEP7QObjectP6QEvent (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x2fc1e9e)
                                                     #11 0x00007f74b55bd0c8 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt6Core.so.6 + 0x1bd0c8)
                                                     #12 0x00007f74b55c086d _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt6Core.so.6 + 0x1c086d)
                                                     #13 0x00007f74b58fcfbf _ZL23postEventSourceDispatchP8_GSourcePFiPvES1_ (libQt6Core.so.6 + 0x4fcfbf)
                                                     #14 0x00007f74b809c9ed g_main_context_dispatch_unlocked (libglib-2.0.so.0 + 0x629ed)
                                                     #15 0x00007f74b809fe78 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0x65e78)
                                                     #16 0x00007f74b80a070f g_main_context_iteration (libglib-2.0.so.0 + 0x6670f)
                                                     #17 0x00007f74b58fc673 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x4fc673)
                                                     #18 0x00007f74b55cae93 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x1cae93)
                                                     #19 0x00007f74b55c5d81 _ZN16QCoreApplication4execEv (libQt6Core.so.6 + 0x1c5d81)
                                                     #20 0x000055bb56a8c089 _ZN4Core8Launcher18executeApplicationEv (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x2f7f089)
                                                     #21 0x000055bb56a8c3b2 _ZN4Core8Launcher4execEv (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x2f7f3b2)
                                                     #22 0x000055bb54b6b325 main (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x105e325)
                                                     #23 0x00007f74b482a4d8 __libc_start_call_main (libc.so.6 + 0x2a4d8)
                                                     #24 0x00007f74b482a59b __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a59b)
                                                     #25 0x000055bb54b77a35 _start (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x106aa35)
                                                     
                                                     Stack trace of thread 2968:
                                                     #0  0x00007f74b335b8cf GetCoeffsFast (libwebp.so.7 + 0xd8cf)
                                                     #1  0x00007f74b335caa1 VP8DecodeMB (libwebp.so.7 + 0xeaa1)
                                                     #2  0x00007f74b335cfaa VP8Decode (libwebp.so.7 + 0xefaa)
                                                     #3  0x00007f74b336196e DecodeInto (libwebp.so.7 + 0x1396e)
                                                     #4  0x00007f74b3361f7e WebPDecodeBGRAInto (libwebp.so.7 + 0x13f7e)
                                                     #5  0x00007f74a40d5022 _ZN12QWebpHandler4readEP6QImage (libqwebp.so + 0x6022)
                                                     #6  0x00007f74b69ba314 _ZN12QImageReader4readEP6QImage.part.0 (libQt6Gui.so.6 + 0x1ba314)
                                                     #7  0x00007f74b69bb178 _ZN12QImageReader4readEv (libQt6Gui.so.6 + 0x1bb178)
                                                     #8  0x00007f74b698ee14 _ZN6QImage4loadERK7QStringPKc (libQt6Gui.so.6 + 0x18ee14)
                                                     #9  0x000055bb59132768 _ZN2Ui5Emoji15UniversalImages12ensureLoadedEv (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x5625768)
                                                     #10 0x000055bb56a1800d _ZN3crl7details4list5EntryIZNKS0_17object_async_baseINS0_12queue_policyEE5asyncIZNS0_17object_async_dataIS4_N8Stickers16EmojiImageLoaderEE4withIZN4Core11Application21startEmojiImageLoaderEvEUlRS9_E_EEvOT_EUlvE_EEvSH_EUlvE_E7ProcessEPNS1_10BasicEntryE (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x2f0b00d)
                                                     #11 0x000055bb55a430be _ZN3crl7details4list7processEv (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x1f360be)
                                                     #12 0x000055bb55a43306 _ZN3crl5queue7processEv (/nix/store/kl9rv75mrkmpkz08w6gal4z4crfjl822-telegram-desktop-6.3.1/bin/.Telegram-wrapped + 0x1f36306)
                                                     #13 0x00007f74b56fbd07 _ZN17QThreadPoolThread3runEv (libQt6Core.so.6 + 0x2fbd07)
                                                     #14 0x00007f74b57a8c9c _ZN14QThreadPrivate5startEPv (libQt6Core.so.6 + 0x3a8c9c)
                                                     #15 0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #16 0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2958:
                                                     #0  0x00007f74b49208bd syscall (libc.so.6 + 0x1208bd)
                                                     #1  0x00007f74b80d3129 g_cond_wait (libglib-2.0.so.0 + 0x99129)
                                                     #2  0x00007f74b8063cab g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x29cab)
                                                     #3  0x00007f74b80d3b8f g_thread_pool_spawn_thread (libglib-2.0.so.0 + 0x99b8f)
                                                     #4  0x00007f74b80d389d g_thread_proxy (libglib-2.0.so.0 + 0x9989d)
                                                     #5  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #6  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2964:
                                                     #0  0x00007f74b49208bd syscall (libc.so.6 + 0x1208bd)
                                                     #1  0x00007f74b80d3610 g_cond_wait_until (libglib-2.0.so.0 + 0x99610)
                                                     #2  0x00007f74b8063c6b g_async_queue_pop_intern_unlocked (libglib-2.0.so.0 + 0x29c6b)
                                                     #3  0x00007f74b80d410a g_thread_pool_thread_proxy (libglib-2.0.so.0 + 0x9a10a)
                                                     #4  0x00007f74b80d389d g_thread_proxy (libglib-2.0.so.0 + 0x9989d)
                                                     #5  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #6  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2963:
                                                     #0  0x00007f74b4897389 __futex_abstimed_wait_common (libc.so.6 + 0x97389)
                                                     #1  0x00007f74b489a031 pthread_cond_timedwait@@GLIBC_2.3.2 (libc.so.6 + 0x9a031)
                                                     #2  0x00007f74b57b16ae _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x3b16ae)
                                                     #3  0x00007f74b56fc16d _ZN17QThreadPoolThread3runEv (libQt6Core.so.6 + 0x2fc16d)
                                                     #4  0x00007f74b57a8c9c _ZN14QThreadPrivate5startEPv (libQt6Core.so.6 + 0x3a8c9c)
                                                     #5  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #6  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2954:
                                                     #0  0x00007f74b4914a10 ppoll (libc.so.6 + 0x114a10)
                                                     #1  0x00007f74b809ff68 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0x65f68)
                                                     #2  0x00007f74b80a070f g_main_context_iteration (libglib-2.0.so.0 + 0x6670f)
                                                     #3  0x00007f74b58fc673 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x4fc673)
                                                     #4  0x00007f74b55cae93 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x1cae93)
                                                     #5  0x00007f74b56f7a29 _ZN7QThread4execEv (libQt6Core.so.6 + 0x2f7a29)
                                                     #6  0x00007f74b8a99041 _ZN22QDBusConnectionManager3runEv (libQt6DBus.so.6 + 0x44041)
                                                     #7  0x00007f74b57a8c9c _ZN14QThreadPrivate5startEPv (libQt6Core.so.6 + 0x3a8c9c)
                                                     #8  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #9  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2960:
                                                     #0  0x00007f74b4914a10 ppoll (libc.so.6 + 0x114a10)
                                                     #1  0x00007f74b809ff68 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0x65f68)
                                                     #2  0x00007f74b80a0967 g_main_loop_run (libglib-2.0.so.0 + 0x66967)
                                                     #3  0x00007f74b514180e gdbus_shared_thread_func (libgio-2.0.so.0 + 0x14180e)
                                                     #4  0x00007f74b80d389d g_thread_proxy (libglib-2.0.so.0 + 0x9989d)
                                                     #5  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #6  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2967:
                                                     #0  0x00007f74b4897389 __futex_abstimed_wait_common (libc.so.6 + 0x97389)
                                                     #1  0x00007f74b489a031 pthread_cond_timedwait@@GLIBC_2.3.2 (libc.so.6 + 0x9a031)
                                                     #2  0x00007f74b57b16ae _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x3b16ae)
                                                     #3  0x00007f74b56fc16d _ZN17QThreadPoolThread3runEv (libQt6Core.so.6 + 0x2fc16d)
                                                     #4  0x00007f74b57a8c9c _ZN14QThreadPrivate5startEPv (libQt6Core.so.6 + 0x3a8c9c)
                                                     #5  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #6  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2959:
                                                     #0  0x00007f74b4914a10 ppoll (libc.so.6 + 0x114a10)
                                                     #1  0x00007f74b809ff68 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0x65f68)
                                                     #2  0x00007f74b80a070f g_main_context_iteration (libglib-2.0.so.0 + 0x6670f)
                                                     #3  0x00007f74b80a0761 glib_worker_main (libglib-2.0.so.0 + 0x66761)
                                                     #4  0x00007f74b80d389d g_thread_proxy (libglib-2.0.so.0 + 0x9989d)
                                                     #5  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #6  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2955:
                                                     #0  0x00007f74b491443d __poll (libc.so.6 + 0x11443d)
                                                     #1  0x00007f74ad417ffd _ZN15QtWaylandClient11EventThread3runEv (libQt6WaylandClient.so.6 + 0x9cffd)
                                                     #2  0x00007f74b57a8c9c _ZN14QThreadPrivate5startEPv (libQt6Core.so.6 + 0x3a8c9c)
                                                     #3  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #4  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2956:
                                                     #0  0x00007f74b491443d __poll (libc.so.6 + 0x11443d)
                                                     #1  0x00007f74ad417ffd _ZN15QtWaylandClient11EventThread3runEv (libQt6WaylandClient.so.6 + 0x9cffd)
                                                     #2  0x00007f74b57a8c9c _ZN14QThreadPrivate5startEPv (libQt6Core.so.6 + 0x3a8c9c)
                                                     #3  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #4  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2970:
                                                     #0  0x00007f74b4914a10 ppoll (libc.so.6 + 0x114a10)
                                                     #1  0x00007f74b809ff68 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0x65f68)
                                                     #2  0x00007f74b80a070f g_main_context_iteration (libglib-2.0.so.0 + 0x6670f)
                                                     #3  0x00007f74b58fc673 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x4fc673)
                                                     #4  0x00007f74b55cae93 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x1cae93)
                                                     #5  0x00007f74b56f7a29 _ZN7QThread4execEv (libQt6Core.so.6 + 0x2f7a29)
                                                     #6  0x00007f74b57a8c9c _ZN14QThreadPrivate5startEPv (libQt6Core.so.6 + 0x3a8c9c)
                                                     #7  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #8  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2961:
                                                     #0  0x00007f74b49231fa epoll_wait (libc.so.6 + 0x1231fa)
                                                     #1  0x00007f74ad3300a2 impl_pollfd_wait (libspa-support.so + 0x1e0a2)
                                                     #2  0x00007f74ad319f5f loop_iterate (libspa-support.so + 0x7f5f)
                                                     #3  0x00007f74bc7c7947 do_loop (libpipewire-0.3.so.0 + 0xbe947)
                                                     #4  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #5  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2957:
                                                     #0  0x00007f74b4914a10 ppoll (libc.so.6 + 0x114a10)
                                                     #1  0x00007f74b809ff68 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0x65f68)
                                                     #2  0x00007f74b80a070f g_main_context_iteration (libglib-2.0.so.0 + 0x6670f)
                                                     #3  0x00007f74b58fc673 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x4fc673)
                                                     #4  0x00007f74b55cae93 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x1cae93)
                                                     #5  0x00007f74b56f7a29 _ZN7QThread4execEv (libQt6Core.so.6 + 0x2f7a29)
                                                     #6  0x00007f74b57a8c9c _ZN14QThreadPrivate5startEPv (libQt6Core.so.6 + 0x3a8c9c)
                                                     #7  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #8  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2969:
                                                     #0  0x00007f74b4914a10 ppoll (libc.so.6 + 0x114a10)
                                                     #1  0x00007f74b809ff68 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0x65f68)
                                                     #2  0x00007f74b80a070f g_main_context_iteration (libglib-2.0.so.0 + 0x6670f)
                                                     #3  0x00007f74b58fc673 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x4fc673)
                                                     #4  0x00007f74b55cae93 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x1cae93)
                                                     #5  0x00007f74b56f7a29 _ZN7QThread4execEv (libQt6Core.so.6 + 0x2f7a29)
                                                     #6  0x00007f74b57a8c9c _ZN14QThreadPrivate5startEPv (libQt6Core.so.6 + 0x3a8c9c)
                                                     #7  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #8  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2965:
                                                     #0  0x00007f74b4897389 __futex_abstimed_wait_common (libc.so.6 + 0x97389)
                                                     #1  0x00007f74b489a031 pthread_cond_timedwait@@GLIBC_2.3.2 (libc.so.6 + 0x9a031)
                                                     #2  0x00007f74b57b16ae _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x3b16ae)
                                                     #3  0x00007f74b56fc16d _ZN17QThreadPoolThread3runEv (libQt6Core.so.6 + 0x2fc16d)
                                                     #4  0x00007f74b57a8c9c _ZN14QThreadPrivate5startEPv (libQt6Core.so.6 + 0x3a8c9c)
                                                     #5  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #6  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2962:
                                                     #0  0x00007f74b49231fa epoll_wait (libc.so.6 + 0x1231fa)
                                                     #1  0x00007f74ad3300a2 impl_pollfd_wait (libspa-support.so + 0x1e0a2)
                                                     #2  0x00007f74ad319f5f loop_iterate (libspa-support.so + 0x7f5f)
                                                     #3  0x00007f74bc7c7947 do_loop (libpipewire-0.3.so.0 + 0xbe947)
                                                     #4  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #5  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2966:
                                                     #0  0x00007f74b4897389 __futex_abstimed_wait_common (libc.so.6 + 0x97389)
                                                     #1  0x00007f74b489a031 pthread_cond_timedwait@@GLIBC_2.3.2 (libc.so.6 + 0x9a031)
                                                     #2  0x00007f74b57b16ae _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt6Core.so.6 + 0x3b16ae)
                                                     #3  0x00007f74b56fc16d _ZN17QThreadPoolThread3runEv (libQt6Core.so.6 + 0x2fc16d)
                                                     #4  0x00007f74b57a8c9c _ZN14QThreadPrivate5startEPv (libQt6Core.so.6 + 0x3a8c9c)
                                                     #5  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #6  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     
                                                     Stack trace of thread 2971:
                                                     #0  0x00007f74b4914a10 ppoll (libc.so.6 + 0x114a10)
                                                     #1  0x00007f74b809ff68 g_main_context_iterate_unlocked.isra.0 (libglib-2.0.so.0 + 0x65f68)
                                                     #2  0x00007f74b80a070f g_main_context_iteration (libglib-2.0.so.0 + 0x6670f)
                                                     #3  0x00007f74b58fc673 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt6Core.so.6 + 0x4fc673)
                                                     #4  0x00007f74b55cae93 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt6Core.so.6 + 0x1cae93)
                                                     #5  0x00007f74b56f7a29 _ZN7QThread4execEv (libQt6Core.so.6 + 0x2f7a29)
                                                     #6  0x00007f74b57a8c9c _ZN14QThreadPrivate5startEPv (libQt6Core.so.6 + 0x3a8c9c)
                                                     #7  0x00007f74b489a97a start_thread (libc.so.6 + 0x9a97a)
                                                     #8  0x00007f74b4922d2c __clone3 (libc.so.6 + 0x122d2c)
                                                     ELF object binary architecture: AMD x86-64
```

**Comment by Leka1B** [comment]
> I tried enabling Cachix again after seeing this comment, and my Vicinae no longer works again for some applications, exactly like before. It also doesn’t seem to suggest my most used applications any more.

I can confirm this still happens.

I have tried replicating vicinae's environment earlier, and it seems to have the paths to older dependency versions, so i don't see this being related to uwsm, and it also happens without it.

My guess is that the paths are hard-coded at build time with everything installed on the system, and the environment used for cachix builds simply might not have the need to pull the newer Qt, etc. This is just a guess though

**Comment by clankus-aurelius** [comment]
@aurelleb this issue may duplicate:

- #674 — Both reports describe specific applications failing silently when launched by a Nix-built Vicinae on NixOS/Hyprland, despite the same desktop command working from a terminal.

_Automated duplicate detection; maintainer confirmation is required._

**Comment by aurelleb** [comment]
Pretty sure we fixed this at some point

**Comment by Diti** [comment]
No, it still happens. The “fix” is to compile Vicinae yourself instead of relying on the Cachix binary. My earlier fix of adding `inputs.nixpkgs.follows = "nixpkgs"` to the Vicinae input kind of does this, because there usually isn’t a cached version available which closely follows the same Nixpkgs input.
