### ISSUE TITLE
Clipboard spontaneosly broke on Debian

### ISSUE THREAD

**Issue by astr64** [vicinaehq/vicinae#711]
Yes, I installed the extension

Description: Debian GNU/Linux 13 (trixie)
6.17.7+deb14+1-amd64 https://github.com/dagimg-dot/vicinae-gnome-extension/issues/1 SMP PREEMPT_DYNAMIC Debian 6.17.7-2 (2025-11-06)
GNOME Shell 48.4

It worked perfectly up until 2 days ago when it decided to crap out and start spewing errors.
I have changed nothing for this to happen.

journalctl /usr/bin/gnome-shell -f -o cat
`[Vicinae] 2025-11-13T12:40:03.519Z INFO: Binary signal emitted: text/plain, 9 bytes`

And running vicinae server
```
[13:41:28.569] INFO   -  GnomeWindowManager: Detected environment: "GNOME/Wayland"
[13:41:28.576] INFO   -  GnomeEventListener: Starting GNOME event listener...
[13:41:28.580] INFO   -  GnomeEventListener: D-Bus connection established successfully
[13:41:28.580] INFO   -  GnomeEventListener: Successfully started and listening for window events
[13:41:28.587] WARN   -  GnomeWindowManager: App database not available for ID mapping
[13:41:28.587] WARN   -  GnomeWindowManager: App database not available for ID mapping
[13:41:28.587] WARN   -  GnomeWindowManager: App database not available for ID mapping
[13:41:28.621] INFO   -  GnomeClipboardServer: GNOME environment detected, checking for extension...
[13:41:28.624] INFO   -  GnomeClipboardServer: GNOME extension detected and available
[13:41:28.625] INFO   -  Activated clipboard server "gnome-clipboard"
I/O warning : failed to load external entity "/usr/share/qalculate/eurofxref-daily.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/prefixes.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/currencies.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/units.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/functions.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/datasets.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/variables.xml"
[13:41:28.729] INFO   -  Killed existing extension manager instance
[13:41:28.730] INFO   -  Started extension manager /run/user/1000/vicinae/extension-manager.js with /usr/local/bin/vicinae-node
[13:41:33.755] WARN   -  Failed to upsert provider with id "extension.clipboard" QSqlError("5", "Unable to fetch row", "database is locked")
[13:41:33.755] WARN   -  Failed to upsert provider
[13:41:38.765] WARN   -  Failed to upsert provider with id "extension.file" QSqlError("5", "Unable to fetch row", "database is locked")
[13:41:38.765] WARN   -  Failed to upsert provider
[13:41:43.776] WARN   -  Failed to upsert provider with id "extension.power" QSqlError("5", "Unable to fetch row", "database is locked")
[13:41:43.776] WARN   -  Failed to upsert provider
[13:41:48.786] WARN   -  Failed to upsert provider with id "extension.raycast-compat" QSqlError("5", "Unable to fetch row", "database is locked")
[13:41:48.786] WARN   -  Failed to upsert provider
```

**Comment by astr64** [comment]
I changed the permissions of all clipboard database files in .local/share/vicinae from their default values to rwx.

I have also spammed restarting the server like a madman, maybe 8 or 9 times.
This suddenly fixed the issue, and another observation is that "vicinae server" actually frees up the terminal - it no longer holds it up like vicinae server previously did. It also finishes with

```
[13:52:42.862] INFO   -  Vicinae server successfully started. Call "vicinae toggle" to toggle the window
[13:52:45.848] INFO   -  Done walking file tree at /home/astr64. Processed 98322 directories and 1090076 files in 3 seconds.
```

which hasn't happened before.

Also worth noting I updated in the process (i used a version earlier than the latest) and that hasn't fixed the problem for me.

**Comment by aurelleb** [comment]
can  you try restarting the vicinae server and see if that still occurs? This suggests that the database is being accessed by two processes at the same time, somehow.
Also, make sure you only have one `vicinae` process running:
```
ps -a | grep -i vicinae
```

**Comment by aurelleb** [comment]
> This suddenly fixed the issue, and another observation is that "vicinae server" actually frees up the terminal - it no longer holds it up like vicinae server previously did. It also finishes with

If you run `vicinae server` manually and you already run it using systemd, then it kills the existing server, and systemd restarts it, effectively killing your `vicinae server` started from the command line. Both shouldn't be used at the same time.

**Comment by astr64** [comment]
@aurelleb I found the issue. It's gotta do with systemd.
If I launch using systemd - the issue persists. The expected behavior should be that it works... on boot. But it doesn't.
Killing it via sudo pkill -fe vicinae and starting manually fully fixes the issue.

Maybe we should diangose the systemd hook?

**Comment by aurelleb** [comment]
I fixed a lock file issue which could allow two servers to run at the same time. As of v0.16.6 this should not be able to occur anymore.

**Comment by astr64** [comment]
> I fixed a lock file issue which could allow two servers to run at the same time. As of v0.16.6 this should not be able to occur anymore.

A temporary workaround I used in the meantime is disabling the systemd hook and using a .desktop file to launch vicinae server on boot in $HOME/.config/autostart

Thanks for the fix!

**Comment by astr64** [comment]
@aurelleb Weirdly, I'm still experiencing this issue. I have no idea what is causing it. And my .config/autostart problem is not fixing it now.

I'm certain the systemd hook is disabled and I am only using the .desktop file to autostart.

I also tried enabling the systemd hook, and disabling the .config/autostart .desktop to no avail

**Comment by aurelleb** [comment]
can you give me the output of that command please?
```
pstree | grep -i vicinae
```

**Comment by astr64** [comment]
> can you give me the output of that command please?
> 
> ```
> pstree | grep -i vicinae
> ```

        |         |-vicinae-+-vicinae-node-+-gnome-control-c
        |         |         |              `-10*[{vicinae-node}]
        |         |         `-13*[{vicinae}]

**Comment by aurelleb** [comment]
and what about the logs, this time?

**Comment by astr64** [comment]
> and what about the logs, this time?

this is from journalctl on gnomeshell
```
Can't update stage views actor unnamed [Gjs_dash-to-dock_micxgx_gmail_com_docking_DashSlideContainer] is on because it needs an allocation.
Can't update stage views actor dashtodockBox [StBoxLayout] is on because it needs an allocation.
Can't update stage views actor bms-dash-backgroundgroup [MetaBackgroundGroup] is on because it needs an allocation.
Can't update stage views actor bms-dash-blurred-widget [StWidget] is on because it needs an allocation.
Can't update stage views actor unnamed [Gjs_dash-to-dock_micxgx_gmail_com_docking_DashSlideContainer] is on because it needs an allocation.
Can't update stage views actor dashtodockBox [StBoxLayout] is on because it needs an allocation.
Can't update stage views actor bms-dash-backgroundgroup [MetaBackgroundGroup] is on because it needs an allocation.
Can't update stage views actor bms-dash-blurred-widget [StWidget] is on because it needs an allocation.
(../libsoup/soup-message-queue-item.c:46):soup_message_queue_item_destroy: runtime check failed: (soup_message_get_connection (item->msg) == NULL)
[Vicinae] 2025-11-23T22:21:23.348Z INFO: Binary signal emitted: text/plain, 41 bytes
```

And this is from vicinae server (pkilled it before running the vicinae server command)
```
[23:22:27.765] INFO   -  Initializing vicinae server...
[23:22:27.775] INFO   -  GnomeEventListener: Starting GNOME event listener...
[23:22:27.777] INFO   -  GnomeEventListener: D-Bus connection established successfully
[23:22:27.777] INFO   -  GnomeEventListener: Successfully started and listening for window events
[23:22:27.778] WARN   -  GnomeWindowManager: App database not available for ID mapping
[23:22:27.778] WARN   -  GnomeWindowManager: App database not available for ID mapping
[23:22:27.778] WARN   -  GnomeWindowManager: App database not available for ID mapping
[23:22:27.778] WARN   -  GnomeWindowManager: App database not available for ID mapping
[23:22:27.791] INFO   -  GnomeClipboardServer: GNOME environment detected, checking for extension...
[23:22:27.792] INFO   -  GnomeClipboardServer: GNOME extension detected and available
[23:22:27.792] INFO   -  Activated clipboard server "gnome-clipboard"
[23:22:27.849] INFO   -  Started extension manager /run/user/1000/vicinae/extension-manager.js with /usr/local/bin/vicinae-node
[23:22:27.852] INFO   -  Starting clipboard server "gnome-clipboard"
[23:22:27.852] INFO   -  GnomeClipboardServer: Starting GNOME clipboard server...
[23:22:27.853] INFO   -  GnomeClipboardServer: D-Bus connection established successfully
[23:22:27.853] INFO   -  GnomeClipboardServer: Successfully started and listening for clipboard changes
[23:22:27.853] INFO   -  Clipboard server "gnome-clipboard" started successfully.
[23:22:27.853] INFO   -  Starting incremental scan for entrypoint /home/astr64
I/O warning : failed to load external entity "/usr/share/qalculate/prefixes.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/currencies.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/units.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/functions.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/datasets.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/variables.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/currencies.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/currencies.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/units.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/variables.xml"
I/O warning : failed to load external entity "/usr/share/qalculate/functions.xml"
[23:22:27.856] INFO   -  Started "Qalculate!" calculator backend
[23:22:27.856] INFO   -  Refreshing Qalculate exchange rates...
[23:22:27.872] WARN   -  Ignoring icon theme directory with no index.theme at /home/astr64/.local/share/icons/boxbuddy/index.theme
[23:22:27.872] WARN   -  Ignoring icon theme directory with no index.theme at /home/astr64/.local/share/icons/hicolor/index.theme
[23:22:27.872] WARN   -  Ignoring icon theme directory with no index.theme at /home/astr64/.local/share/icons/AdwaitaLegacy/index.theme
[23:22:27.872] WARN   -  Ignoring icon theme directory with no index.theme at /home/astr64/.local/share/icons/distrobox/index.theme
[23:22:27.872] WARN   -  Ignoring icon theme directory with no index.theme at /home/astr64/.local/share/icons/Adwaita/index.theme
[23:22:27.872] WARN   -  Ignoring icon theme directory with no index.theme at /usr/local/share/icons/hicolor/index.theme
[23:22:27.873] WARN   -  Ignoring icon theme directory with no index.theme at /usr/share/icons/mozc/index.theme
[23:22:27.873] WARN   -  Ignoring icon theme directory with no index.theme at /usr/share/icons/vendor/index.theme
[23:22:27.873] WARN   -  Ignoring icon theme directory with no index.theme at /usr/share/icons/locolor/index.theme
[23:22:27.873] WARN   -  Ignoring icon theme directory with no index.theme at /usr/share/icons/desktop-base/index.theme
[23:22:28.115] INFO   -  Vicinae server successfully started. Call "vicinae toggle" to toggle the window
[23:22:30.857] INFO   -  Done walking file tree at /home/astr64. Processed 112137 directories and 1273608 files in 3 seconds.
[23:22:33.264] WARN   -  Failed to refresh exchange rates Failed to fetch exchange rates
```


Worth noting, after killing the vicinae process tree and re-running the server from the current user, everything works as expected.

**Comment by astr64** [comment]
@aurelleb I am still facing this despite being on the latest version. Any ideas on what's causing it?

**Comment by z0xca** [comment]
> [@aurelleb](https://github.com/aurelleb) I am still facing this despite being on the latest version. Any ideas on what's causing it?

Are you using the swww-switcher extension by any chance? https://github.com/vicinaehq/vicinae/issues/873
If so, it was fixed in v0.17.2 https://github.com/vicinaehq/vicinae/pull/874

**Comment by astr64** [comment]
Issue has been fully fixed in the latest version.
