### ISSUE TITLE
Extension installation fails with empty package.json and minizip conflicts with `vicinae-bin`

### ISSUE THREAD

**Issue by jason-curtis** [vicinaehq/vicinae#813]
## Description

All extension installations fail when attempting to install any extension from the Vicinae or Raycast store. Extensions are downloaded but the installation process fails, leaving behind extracted files with **empty package.json files** (0 bytes).

This is occurring on a **fresh Omarchy install** with newly installed Vicinae via `yay -S vicinae-bin`.

## System Information

- **Vicinae Version:** v0.16.11 (commit 05cbd00db, GCC 14.3.1)
- **OS:** Arch Linux (Linux 6.17.8-arch1-1)
- **Desktop:** Wayland
- **Setup:** Fresh Omarchy installation with Vicinae

## Error Logs

```
[21:23:58.640] ERROR  -  Failed to load bundle at /home/jason/.local/share/vicinae/extensions/store.vicinae.wifi-commander "Failed to parse package.json at /home/jason/.local/share/vicinae/extensions/store.vicinae.wifi-commander/package.json"
[21:23:58.640] ERROR  -  Failed to load bundle at /home/jason/.local/share/vicinae/extensions/store.vicinae.bluetooth "Failed to parse package.json at /home/jason/.local/share/vicinae/extensions/store.vicinae.bluetooth/package.json"
[21:23:58.640] ERROR  -  Failed to load bundle at /home/jason/.local/share/vicinae/extensions/store.vicinae.omarchy-menu "Failed to parse package.json at /home/jason/.local/share/vicinae/extensions/store.vicinae.omarchy-menu/package.json"
[21:24:19.498] WARN   -  Failed to open ziped file QDir( "bluetooth/scan.js" , ... )
[21:24:19.498] WARN   -  Failed to open ziped file QDir( "bluetooth/assets/Preview_Scan.png" , ... )
[21:24:19.499] WARN   -  Failed to open ziped file QDir( "bluetooth/devices.js" , ... )
[21:24:19.499] WARN   -  Failed to open ziped file QDir( "bluetooth/package.json" , ... )
```

## Root Cause Analysis

The issue appears related to the December 4, 2025 build changes (#810: "build: do not link against minizip statically for portable builds") which switched to using the system's installed minizip library instead of bundling it.

**Installed libraries:**
- `minizip 1:1.3.1-2`
- `minizip-ng 4.0.10-1` (conflicting package)

The presence of both `minizip` and `minizip-ng` may be causing the build to link against the wrong library, or there may be a compatibility issue with one of these versions.

## Steps to Reproduce

1. Start Vicinae server
2. Open the extension store
3. Try to install any extension (e.g., wifi-commander, bluetooth, omarchy-menu)
4. Observe installation failure with empty package.json in the extensions directory

## Expected Behavior

Extensions should install successfully with valid, populated package.json files and be immediately usable.

## Additional Notes

- This issue affects **all extensions** regardless of source (Vicinae store, Raycast store)
- The extracted extension files are present on disk but unusable due to empty manifests
- Similar issue was fixed in PR #695 with a temp file flush, but that shouldn't affect this scenario

**Comment by jason-curtis** [comment]
I just tried using the `vicinae` package rather than `vicinae-bin` and it looks like that resolved the issue for me.

**Comment by saatvik333** [comment]
Facing the same issue

**Comment by aurelleb** [comment]
please try with latest release, this should be fixed

**Comment by saatvik333** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/68a82bc1-c314-417e-bf0b-e0b83dc88788" />
It didn't fix

**Comment by saatvik333** [comment]
Even with the `vicinae` package

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/12e347be-b438-4823-a800-01d49b527c1e" />
Same issue

**Comment by jason-curtis** [comment]
@saatvik333 did you try reinstalling the extension now that you have the new `vicinae` version installed? The issue is in the extension install phase so if you still have the broken install from the old `vicinae-bin` it will not work. Just install again

**Comment by saatvik333** [comment]
How can I remove all the elements of vicinae on my device? I tried clearing `~/.cache/vicinae` along with clean-build reinstall using the package manager.

How to completely reset and reinstall it from scratch?

**Comment by saatvik333** [comment]
Alright, the v0.16.12 fixed that 
I used the `vicinae-git` package

**Comment by aurelleb** [comment]
Fixed
